import { StyleSheet } from 'react-native';
import { radius, spacing, typography } from '../../theme';
import { useTheme } from '../../ThemeContext';

export function useTimerStyles() {
  const { colors } = useTheme();
  return { styles: makeStyles(colors), colors };
}

const makeStyles = (colors) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerLight: { borderBottomColor: 'rgba(255,255,255,0.2)' },
  headerCenter: { flex: 1, alignItems: 'center' },
  headerDay: { ...typography.body, fontWeight: '700' },
  headerType: { ...typography.bodySmall },
  headerDist: { minWidth: 48, alignItems: 'flex-end' },
  headerDistText: { ...typography.body, fontWeight: '700', color: colors.primary },
  content: { padding: spacing.md, paddingBottom: spacing.xxl, alignItems: 'center' },

  dotsRow: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    marginBottom: spacing.sm,
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  dot: { borderRadius: 99 },
  phaseCounter: { ...typography.label, marginBottom: spacing.lg, color: colors.textSecondary },

  timerBlock: { alignItems: 'center', width: '100%', marginBottom: spacing.lg },
  phaseCard: {
    alignSelf: 'stretch',
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    alignItems: 'center',
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  // Active state: dark tint integrates with phase color, no shadow/border artifacts on Android
  phaseCardActive: {
    backgroundColor: 'rgba(0,0,0,0.18)',
    elevation: 0,
    shadowOpacity: 0,
  },
  phaseLabel: { fontSize: 26, fontWeight: '800', letterSpacing: 3, color: colors.text },
  timerBig: {
    fontSize: 92,
    fontWeight: '200',
    color: colors.text,
    letterSpacing: -2,
    fontVariant: ['tabular-nums'],
  },
  timerSub: { ...typography.bodySmall, color: colors.textSecondary, marginTop: -spacing.sm },
  phaseTrack: {
    width: '80%',
    height: 4,
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: 2,
    overflow: 'hidden',
    marginTop: spacing.xs,
  },
  phaseFill: { height: '100%', borderRadius: 2 },
  targetPaceRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: spacing.xs },
  targetPaceText: { fontSize: 13, fontWeight: '600', color: 'rgba(255,255,255,0.85)' },
  paceTipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: spacing.xs,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.2)',
    width: '100%',
    justifyContent: 'center',
  },
  paceTipText: { fontSize: 13, color: 'rgba(255,255,255,0.85)', fontWeight: '500', textAlign: 'center' },
  totalTimer: { marginTop: spacing.md, fontSize: 14, fontWeight: '600', color: 'rgba(255,255,255,0.8)' },

  nextBlock: { width: '100%', marginBottom: spacing.lg },
  nextLabel: { ...typography.label, marginBottom: spacing.xs, color: 'rgba(255,255,255,0.7)' },
  nextCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: radius.md,
    padding: spacing.sm,
    borderLeftWidth: 3,
  },
  nextText: { flex: 1, fontWeight: '600', color: '#fff', fontSize: 14 },
  nextDuration: { fontWeight: '700', color: 'rgba(255,255,255,0.8)', fontSize: 13 },

  descBox: {
    flexDirection: 'row',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    width: '100%',
    marginBottom: spacing.lg,
  },
  descText: { ...typography.body, flex: 1, color: colors.textSecondary, lineHeight: 22 },

  controls: { alignItems: 'center', gap: spacing.md, width: '100%' },
  btnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: spacing.sm,
  },
  sideBtn: {
    alignItems: 'center',
    gap: 4,
    minWidth: 72,
    paddingVertical: spacing.xs,
  },
  sideBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.65)',
    textAlign: 'center',
  },
  bigPlayBtn: {
    width: 160,
    height: 160,
    borderRadius: 80,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  bigPlayText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  mainBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.full,
    minWidth: 180,
  },
  mainBtnText: { fontSize: 16, fontWeight: '700' },
  skipBtn: { paddingVertical: spacing.xs },
  skipText: { ...typography.body, fontWeight: '600' },
  finishBtn: { paddingVertical: spacing.xs },
  finishText: { ...typography.bodySmall },

  countdownOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  countdownNum: { fontSize: 128, fontWeight: '800', color: '#fff', lineHeight: 140 },
  countdownLabel: {
    fontSize: 20,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginTop: spacing.sm,
  },

  planView: {
    width: '100%',
    marginBottom: spacing.lg,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    overflow: 'hidden',
  },
  planViewLabel: {
    ...typography.label,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  planRow: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.border, minHeight: 52 },
  planRowBar: { width: 4 },
  planRowBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  planRowLeft: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, flex: 1 },
  planRowName: { fontSize: 13, fontWeight: '600', color: colors.text },
  planRowSlash: { fontSize: 13, color: colors.textSecondary, marginHorizontal: 2 },
  planRowDur: { fontSize: 13, fontWeight: '700', color: colors.text },
  planViewTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  planViewTotalLabel: { ...typography.label },
  planViewTotalValue: { fontSize: 15, fontWeight: '800', color: colors.primary },
});
